-- 01
CREATE TABLE CUSTOMERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(128) NOT NULL,
    LASTNAME VARCHAR(155) NOT NULL,
    PHONE VARCHAR(16) NOT NULL,
    EMAIL VARCHAR(32) NOT NULL,
    ADDRESS VARCHAR(200) NOT NULL,
    CITY VARCHAR(64) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    BIRTH_DATE DATETIME NOT NULL
);

-- 02
CREATE TABLE CAR_MODELS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MODEL_NAME VARCHAR(120) NOT NULL
);

-- 03
CREATE TABLE CAR_BRANDS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    BRAND_NAME VARCHAR(32) NOT NULL
);

-- 04
CREATE TABLE POSITIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DESCRIPTION VARCHAR(120) NOT NULL
);

-- 05
CREATE TABLE EMPLOYEES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(16) NOT NULL,
    CONTRACT_DATE DATETIME NOT NULL,
    POSITION_ID INTEGER,
    FOREIGN KEY (POSITION_ID) REFERENCES POSITIONS (ID)
);

-- 06
CREATE TABLE CARS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(120) NOT NULL,
    YEAR INTEGER,
    COLOR VARCHAR(32) NOT NULL,
    KM DECIMAL(10,2) NOT NULL,
    STATUS VARCHAR(17) NOT NULL,
    BRAND_ID INTEGER,
    MODEL_ID INTEGER,
    FOREIGN KEY (BRAND_ID) REFERENCES CAR_BRANDS (ID),
    FOREIGN KEY (MODEL_ID) REFERENCES CAR_MODELS (ID)
);

-- 07
CREATE TABLE LOCATIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    TOTAL DECIMAL(10,2) NOT NULL,
    CUSTOMER_ID INTEGER,
    CAR_ID INTEGER,
    EMPLOYEE_ID INTEGER,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID),
    FOREIGN KEY (CAR_ID) REFERENCES CUSTOMERS (ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID)
);
