-- 01
UPDATE CUSTOMERS SET EMAIL = 'carolina@campuscode.com.br' WHERE ID = 9;

-- 02
UPDATE CUSTOMERS SET BIRTH_DATE = '1986-06-19' WHERE ID = 4;

-- 03
UPDATE CARS SET YEAR = 2019 WHERE ID = 4;

-- 04
DELETE FROM CARS WHERE ID = 2;

-- 05
ALTER TABLE EMPLOYEES
    RENAME COLUMN PHONE TO PHONE_NUMBER;