-- SQLite

-- TABELA SALES (VENDAS)
CREATE TABLE ITEM_SALES(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SALE_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    QTD INTEGER NOT NULL,
    SUBTOTAL DECIMAL (10,2) NOT NULL,

    FOREIGN KEY (SALE_ID) REFERENCES SALES (ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID)
);


DROP TABLE ITEM_SALES;

SELECT * FROM ITEM_SALES;


